CREATE TABLE MANAGER (
    ID         NUMBER(3)     NOT NULL,
    NAME       VARCHAR2(100) DEFAULT 'NO NAME',
    AGE        NUMBER(3)     NOT NULL,
    BIRTH_DATE DATE          DEFAULT SYSDATE NOT NULL,
    ADDRESS    VARCHAR2(244) DEFAULT 'NO ADDRESS'
);