-- CREATE TABLE NAMED MANAGER AND ADD SOME COLUMNS.

CREATE TABLE MANAGER (

    ID         NUMBER(3)     NOT NULL,
    NAME       VARCHAR2(100) DEFAULT 'NO NAME',
    AGE        NUMBER(3)     NOT NULL,
    BIRTH_DATE DATE          DEFAULT sysdate NOT NULL,
    ADDRESS    VARCHAR2(244) DEFAULT 'NO ADDRESS'
);

-- DROP COLUMN ADDRESS FROM TABLE MANAGER.

ALTER TABLE MANAGER DROP COLUMN ADDRESS ;

-- ADD TWO COLUMNS TO THE TABLE (CITY ADDRESS , STREET ) TO THE TABLE.
 ALTER TABLE MANAGER ADD (CITY_ADDRESS VARCHAR2(100) , STREET VARCHAR(100));

-- MODIFY  A COLUMN NAME  .
ALTER TABLE MANAGER  RENAME COLUMN  NAME TO FULL_NAME;

-- MAKE THE TABLE READ ONLY

ALTER TABLE MANAGER READ ONLY;

-- CREATE A COPY TABLE FROM TABLE MANAGE WITH SOME COLUMNS.

CREATE TABLE OWNER AS SELECT ID,FULL_NAME,BIRTH_DATE FROM MANAGER;


-- RENAME MANAGER TABLE TO MASTER
ALTER TABLE MANAGER RENAME TO MASTER;

-- DROP ALL THE TABLE (MASTER , OWNER)
DROP TABLE MASTER;
DROP TABLE OWNER;  

-- SELECT * FROM MANAGER;